### ISSUE TITLE
Stoped working

### ISSUE THREAD

**Issue by michaldaniel** [cybre/imgur-contract#2]
I would love to tell you more but it doesn't give much of debugging info.
The context menu element is still present but nothing happens upon clicking it.

**Comment by cybre** [comment]
Run `/usr/share/ImgurContract/upload.py /path/to/an/image.png` and post the output here.

**Comment by michaldaniel** [comment]
It is the same output as I had with elementary+ icons configurator [you answered recently](https://github.com/cybre/imgur-contract/issues/2#issuecomment-170372640). 
`gi.RepositoryError: Typelib file for namespace 'GdkPixbuf', version '2.0' not found`
